from manager import Mazo, Oro,Aliado, Arma, Talisman,Totem



if __name__ == "__main__":
    mazo_heroe = Mazo()
    mazo_heroe.add_oro_inicial(Oro("Universidad Cosmografia","Oro Inicial. Sólo se pueden buscar y/o Robar cartas por efectos hasta dos veces por turno. Los jugadores deben Desterrar una carta de su mano para jugar una carta sin pagar su coste. Este Oro no puede perder su habilidad."))
    mazo_heroe.add_card(Oro("Hidromiel","Cuando entra en juego, Baraja hasta tres cartas de un Cementerio y Roba dos cartas."))
    mazo_heroe.add_card(Oro("Pendiente Pirata","Una vez en tu Vigilia, puedes mover este Oro a tu Oro Pagado para buscar un Arma o Tótem en tu Castillo. Luego, genera un Oro para jugar Armas o Tótem de coste 2 o más. Tus demás Oros no pueden perder su habilidad y no son afectados por Talismanes."))
    mazo_heroe.add_card(Oro("Calavera Coronada","Cuando entra en juego, puedes Destruir una carta de coste 1 o menos. Luego, Purifica hasta dos cartas de los Cementerios. Al comienzo de tu Fase Final, puedes Descartar una carta para Robar una carta."))
    mazo_heroe.add_card(Oro("Piedra Cintamani","Si entra en juego en tu primer o segundo turno, busca un Arma, Oro o Tótem en tu Castillo. De lo contrario, Roba una carta. Puedes Desterrarlo para cancelar el ataque oponente."))
    mazo_heroe.add_card(Oro("Piedra Cintamani","Si entra en juego en tu primer o segundo turno, busca un Arma, Oro o Tótem en tu Castillo. De lo contrario, Roba una carta. Puedes Desterrarlo para cancelar el ataque oponente."))
    mazo_heroe.add_card(Oro("Piedra Cintamani","Si entra en juego en tu primer o segundo turno, busca un Arma, Oro o Tótem en tu Castillo. De lo contrario, Roba una carta. Puedes Desterrarlo para cancelar el ataque oponente."))
    mazo_heroe.add_card(Oro("Sigillum Dei", "Puedes Desterrar este Oro de tu Reserva para poner un Oro de tu Castillo en tu Reserva. Cuando pagues el coste de un Aliado con este Oro, puedes Purificar hasta tantas cartas como Fuerza tenga ese Aliado."))
    mazo_heroe.add_card(Oro("Manzanas Doradas","En tu Fase Final, si está en tu Reserva, puedes poner la primer o última carta de tu Castillo en tu mano. Al comienzo de tu Vigilia, si controlas menos Aliados que tu oponente, Genera un Oro para jugar un Arma o Tótem."))
    mazo_heroe.add_card(Oro("Manzanas Doradas","En tu Fase Final, si está en tu Reserva, puedes poner la primer o última carta de tu Castillo en tu mano. Al comienzo de tu Vigilia, si controlas menos Aliados que tu oponente, Genera un Oro para jugar un Arma o Tótem."))
    mazo_heroe.add_card(Oro("Cantar del Mio Cid","Errante. Al comienzo de tu Vigilia, puedes mirar la primera carta de tu Castillo y elegir ponerlo en tu mano o Cementerio. Si controlas más Aliados que tu oponente, en vez de eso puedes subir una carta al azar de tu Cementerio a tu mano."))
    mazo_heroe.add_card(Oro("Dulce Mermelada","Luz. Errante (Sólo puedes controlar una copia de esta carta). Cuando entra en juego, busca un Oro en tu Castillo y ponlo en tu mano. En tu Fase Final, puedes Barajar una carta de tu mano para Agrupar otro Oro que controles."))
    mazo_heroe.add_card(Oro("Tesoro","Errante. Si está en tu Reserva, los Aliados en los Cementerios pierden su habilidad. Puedes pagarlo para Purificar hasta dos cartas de los Cementerios y Robar dos cartas. Este turno no puedes Robar en tu Fase de Robar."))
    mazo_heroe.add_card(Arma("Dromón Sarraceno","El portador gana 3 de Fuerza. En tu Fase Final, si el portador hace daño de combate puedes agrupar un Aliado y un Oro que controles. Luego, Purifica hasta tantas cartas como fuerza tenga el portador o Roba dos cartas.",1))
    mazo_heroe.add_card(Arma("Guillotina","Maquinaria. Tamaño 1. Gana el control de un Aliado de coste 2 o menos y en tu Fase Final, Destiérralo. Puedes Desterrar una carta de tu Cementerio para subir esta Arma de tu Cementerio a tu mano.",1))
    mazo_heroe.add_card(Arma("Mosquete Nock","Si está en tu Cementerio, puedes pagar un Oro para jugarla. El portador gana 2 de Fuerza, Furia e Imbloqueable. En Asignación de Daño, puedes Purificar hasta tantas cartas como daño haga el portador.",0))
    mazo_heroe.add_card(Arma("Mosquete Nock","Si está en tu Cementerio, puedes pagar un Oro para jugarla. El portador gana 2 de Fuerza, Furia e Imbloqueable. En Asignación de Daño, puedes Purificar hasta tantas cartas como daño haga el portador.",0))
    mazo_heroe.add_card(Arma("Tizona","Errante. El portador gana 2 Fuerza e Indestructible. Cuando entra en juego, Roba una carta. Puedes Desterrarla para Anular un Talismán o cancelar una habilidad oponente.",1))
    mazo_heroe.add_card(Totem("Salem","Tu oponente no puede jugar Talismanes a menos que Destierre dos cartas de su Castillo. Cuando resuelvas un Talismán, puedes Descartar una carta para volver a repetir su efecto. Si Descartaste una Bruja, además puedes Destruir una carta que no sea Oro.",2))
    mazo_heroe.add_card(Totem("Torre de Oro","Cuando entra en juego, Purifica hasta dos cartas de los Cementerios y Roba dos cartas. Puedes Desterrarlo de tu mano o Destruirlo para cambiar los objetivos de un Talismán o habilidad.",1))
    mazo_heroe.add_card(Talisman("Carro de la Muerte","Exhumar. Puedes Desterrar un Oro que controles para jugar este Talismán sin pagar su coste y Destiérralo. Busca un Oro y tu oponente Bota siete cartas.",2))
    mazo_heroe.add_card(Talisman("Bloque de Hielo","En respuesta a que una carta fuera a ser puesta en juego, si no se pagó su coste, puedes poner este Tótem en juego. Cuando entra en juego, Roba dos cartas. No se puede jugar cartas sin pagar su coste ni poner cartas en juego sin pagar su coste.",1))
    mazo_heroe.add_card(Talisman("Oráculo de Delfos","Exhumar. Cuando lo juegues, Destiérralo. Cancela la habilidad de una carta. Este turno, la próxima habilidad que utilice tu oponente de una carta del mismo tipo, cuesta un Oro adicional",1))
    mazo_heroe.add_card(Talisman("Caligrafía","No puede ser Anulado. Anula o Destierra una carta de coste 1 o menos y Roba una carta. Tu oponente puede pagar dos Oros para que este Talismán se resuelva sin efecto.",1))
    mazo_heroe.add_card(Talisman("Caligrafía","No puede ser Anulado. Anula o Destierra una carta de coste 1 o menos y Roba una carta. Tu oponente puede pagar dos Oros para que este Talismán se resuelva sin efecto.",1))
    mazo_heroe.add_card(Talisman("Aliento de Muerte","Destierra un Aliado de tu mano. Luego, Destruye una carta oponente y Roba dos cartas. Si Destruiste un Oro de esta forma tu oponente puede buscar en su Castillo un Oro sin habilidad y ponerlo en su Oro Pagado.",2))
    mazo_heroe.add_card(Talisman("Encuentro de dos Mundos","Sólo puedes jugar Encuentro de dos Mundos por turno y si sólo controlas Aliados. Mira la mano de tu oponente y elige una carta de ahí que no sea Oro. Puedes Desterrarla y Robar dos cartas o jugarla sin pagar su coste. En tu Fase Final, Agrupa un Oro.",1))
    mazo_heroe.add_card(Talisman("Arqueros Letales","Sólo puedes jugar un Arqueros Letales por turno y Destiérralo. Tus Aliados no pueden salir del juego por el turno y Roba una carta por cada Bárbaro, Caballero, Guerrero y/o Héroe que controles. Tu oponente Bota cuatro cartas.",1))
    mazo_heroe.add_card(Talisman("Arqueros Letales","Sólo puedes jugar un Arqueros Letales por turno y Destiérralo. Tus Aliados no pueden salir del juego por el turno y Roba una carta por cada Bárbaro, Caballero, Guerrero y/o Héroe que controles. Tu oponente Bota cuatro cartas.",1))
    mazo_heroe.add_card(Talisman("Perseguir el Sol","",3))
    mazo_heroe.add_card(Talisman("Elli","Los Aliados oponentes pierden su habilidad y tienen Fuerza 0 hasta el final de tu próximo turno. Cuando sea puesto en tu Cementerio, puedes Desterrarlo para Barajar un Aliado de coste 1 o menos.",2))
    mazo_heroe.add_card(Talisman("Hacer el bien","Única. Exhumar. Anula una carta de coste 3 o menos.",1))
    mazo_heroe.add_card(Talisman("Caída del Arcángel","Única. Si controlas dos o más Aliados de una misma Raza, no puede ser Anulado. Cuando lo juegues, Destiérralo. Anula una carta o cancela una habilidad.",1))
    mazo_heroe.add_card(Talisman("Jack en el Verde","Única. Exhumar. Cuando juegues este Talismán, Destiérralo. Anula o Baraja una carta de coste 2 o menos. Luego, Roba dos cartas.",1))
    mazo_heroe.add_card(Talisman("Expulsion","Puedes jugar este Talismán en respuesta a que tu oponente juegue una carta.Esa carta entra en juego sin habilidad por el turno. Si es un Talismán, esa carta se resuelve sin efecto. Puedes Desterrarla de tu Cementerio para que una carta pierda su habilidad por el turno.",1))
    mazo_heroe.add_card(Aliado("Leonardo Eterno","Indestructible. Puedes nombrar una carta que no sea Oro. Mira la mano de tu oponente y Descarta una carta de ahí con el mismo nombre. Las cartas oponentes que no sean Aliado ni Oro cuestan un Oro adicional.",4,2))
    mazo_heroe.add_card(Aliado("Fergus","Indestructible. Una vez en tu Vigilia, puedes Desterrar una carta oponente que no sea Oro. Luego, busca una carta del mismo tipo en tu Castillo y ponla en tu mano. Los Oros en juego pierden su habilidad.",3,2))
    mazo_heroe.add_card(Aliado("Fergus Z","Indestructible. Cuando entra en juego, mira la mano de tu oponente y Destierra un Talismán de ahí. Una vez en tu Vigilia, Destruye el Aliado oponente de mayor Fuerza.",3,2))
    mazo_heroe.add_card(Aliado("Thor Asabrag","Cuando entra en juego, puedes buscar un Aliado Héroe y un Arma en tu Castillo y ponerlas en tu mano. En tu Vigilia, una vez por turno, puedes hacer que un Aliado que controles haga doble daño de combate este turno.",3,1))
    mazo_heroe.add_card(Aliado("Thor Asabrag","Cuando entra en juego, puedes buscar un Aliado Héroe y un Arma en tu Castillo y ponerlas en tu mano. En tu Vigilia, una vez por turno, puedes hacer que un Aliado que controles haga doble daño de combate este turno.",3,1))
    mazo_heroe.add_card(Aliado("El Mio Cid","Errante. Furia. Cuando entra en juego, crea una Espada y portala. Puedes Destruir un Arma que controles para Robar dos cartas o pagar un Oro oponente. Puedes jugar un Arma de coste 1 o menos de tu mano o Castillo, sin pagar su coste.",4,2))
    mazo_heroe.add_card(Aliado("Dante Allighieri","Errante. Guardián. En tu Vigilia, puedes generar un Oro para jugar Héroes y que no pueda ser Anulado. Luego, Roba una carta. Puedes Desterrar una carta de tu Castillo para prevenir un efecto que fuera a afectar tus cartas.",5,2))
    mazo_heroe.add_card(Aliado("Lord Byron","Furia. Indestructible. Puedes hacer que un Aliado haga doble daño este turno y Purificar hasta cuatro cartas. Cuando tu oponente pague un Oro en tu turno, pon en juego un Aliado o Arma de tu mano o Cementerio, de coste 1 o menos.",4,2))
    mazo_heroe.add_card(Aliado("Newton","Furia. Indestructible. Al comienzo de tu Fase Final, tu oponente puede pagar un Oro, de lo contrario, elige entre Barajar todos sus Aliados en juego o ver su mano y Barajar todos los Talismanes de ahí. En tu Vigilia, puedes Robar dos cartas.",4,2))
    mazo_heroe.add_card(Aliado("Newton","Furia. Indestructible. Al comienzo de tu Fase Final, tu oponente puede pagar un Oro, de lo contrario, elige entre Barajar todos sus Aliados en juego o ver su mano y Barajar todos los Talismanes de ahí. En tu Vigilia, puedes Robar dos cartas.",4,2))
    mazo_heroe.add_card(Aliado("Newton","Furia. Indestructible. Al comienzo de tu Fase Final, tu oponente puede pagar un Oro, de lo contrario, elige entre Barajar todos sus Aliados en juego o ver su mano y Barajar todos los Talismanes de ahí. En tu Vigilia, puedes Robar dos cartas.",4,2))
    mazo_heroe.add_card(Aliado("Magallanes","Furia. Indestructible. En tu Vigilia, tu oponente puede pagar un Oro para que no pueda ser declarado atacante. Cuando ataque, mira la mano oponente y Destierra una carta de ahí que no sea Oro.",4,2))
    mazo_heroe.add_card(Aliado("Hilda","Furia. Cuando ataca, puedes Barajar hasta dos cartas oponentes que no sea Oro o hacer que un Aliado Héroe gane 3 de Fuerza y haga doble daño de combate este turno.",3,3))
    mazo_heroe.add_card(Aliado("Vidarr","Furia. Cuando ataca, tu oponente Baraja una carta de su mano. Luego, un Aliado Héroe que controles hace doble daño de combate este turno.",3,1))
    mazo_heroe.add_card(Aliado("El Cid","Furia. Imbloqueable. Entra en juego como un Caballero o Héroe. Puedes jugar Tizona de tu Castillo o un Aliado hace doble daño de combate este turno. Cuando entra en juego o haga daño, Baraja hasta dos cartas oponentes que no sean Oro.",4,2))
    
    mazo_heroe.mezclar_mazo()

    mazo_eterno = Mazo()
    mazo_eterno.add_oro_inicial(Oro("Las Partidas",""))
    mazo_eterno.add_card(Oro("Aegishjalmur",""))
    mazo_eterno.add_card(Oro("Bracteate",""))
    mazo_eterno.add_card(Oro("Futhark Antiguo",""))
    mazo_eterno.add_card(Oro("Alicanto",""))
    mazo_eterno.add_card(Oro("Cuerno de Pólvora",""))
    mazo_eterno.add_card(Oro("Gullgubber",""))
    mazo_eterno.add_card(Oro("Manzanas Doradas",""))
    mazo_eterno.add_card(Oro("Manzanas Doradas",""))
    mazo_eterno.add_card(Oro("Amuleto de Thor",""))
    mazo_eterno.add_card(Oro("Laterna",""))
    mazo_eterno.add_card(Oro("Laterna",""))
    mazo_eterno.add_card(Oro("Parche Pirata",""))
    mazo_eterno.add_card(Oro("Puertas del Valhalla",""))
    mazo_eterno.add_card(Oro("Nycticorax",""))
    mazo_eterno.add_card(Arma("Espada Vikinga","",1))
    mazo_eterno.add_card(Talisman("Hacer el Bien","",1))
    mazo_eterno.add_card(Talisman("Destruir el Puerto","",2))
    mazo_eterno.add_card(Talisman("Blasfemia","",1))
    mazo_eterno.add_card(Talisman("Fantasmas del Desierto","",1))
    mazo_eterno.add_card(Talisman("Trempulcahue","",2))
    mazo_eterno.add_card(Talisman("Jack en el Verde","",1))
    mazo_eterno.add_card(Talisman("Expulsión","",1))
    mazo_eterno.add_card(Talisman("Nav","",0))
    mazo_eterno.add_card(Talisman("Ahí Viene la Reina","",0))
    mazo_eterno.add_card(Talisman("Caída del Arcángel","",1))
    mazo_eterno.add_card(Talisman("Caligrafía","",1))
    mazo_eterno.add_card(Talisman("Caligrafía","",1))
    mazo_eterno.add_card(Totem("Templo de Uppsala","",1))
    mazo_eterno.add_card(Totem("Templo de Uppsala","",1))
    mazo_eterno.add_card(Totem("Templo de Uppsala","",1))
    mazo_eterno.add_card(Totem("Califato de Córdoba","",1))
    mazo_eterno.add_card(Aliado("San Jorge","",3,1))
    mazo_eterno.add_card(Aliado("San Jorge","",3,1))
    mazo_eterno.add_card(Aliado("San Jorge","",3,1))
    mazo_eterno.add_card(Aliado("Cronos","",5,3))
    mazo_eterno.add_card(Aliado("Santiago","",0,1))
    mazo_eterno.add_card(Aliado("Heindal","",3,1))
    mazo_eterno.add_card(Aliado("Heindal","",3,1))
    mazo_eterno.add_card(Aliado("Antiguo","",0,1))
    mazo_eterno.add_card(Aliado("Al-Qaum","",3,1))
    mazo_eterno.add_card(Aliado("Tulzcka","",3,1))
    mazo_eterno.add_card(Aliado("Lugus","",3,1))
    mazo_eterno.add_card(Aliado("Arzael el Destructor","",3,1))
    mazo_eterno.add_card(Aliado("Arzael el Destructor","",3,1))
    mazo_eterno.add_card(Aliado("Arzael el Destructor","",3,1))
    mazo_eterno.add_card(Aliado("Lilith","",3,1))
    mazo_eterno.add_card(Aliado("Sombrerero Loco","",3,1))
    mazo_eterno.add_card(Aliado("Eolos","",3,1))
    mazo_eterno.add_card(Aliado("Odin","",3,1))
    
    mazo_eterno.mezclar_mazo()

    #mazo_heroe.show_deck()
    #mazo_eterno.show_deck()

    #print(mazo_heroe.count())
    #mazo_heroe.draw_mano_inicial()
    #Juego.mulligan_prompt(mazo_heroe)


    print(mazo_eterno.count())
    print(type(mazo_eterno.draw_mano_inicial()))
    pivot_mazo = mazo_eterno
    casos = {}
    for i in range(10):
        pivot_mazo.mezclar_mazo()
        print(pivot_mazo.count())
        casos[i] = pivot_mazo.draw_mano_inicial()
        pivot_mazo = mazo_eterno
    print cas